### ISSUE TITLE
Running the modeler on EclipseLuna

### ISSUE THREAD

**Issue by guihomework** [konradb3/control-modeler#2]
Dear developer @konradb3 

while looking at https://github.com/RCPRG-ros-pkg/lwr_robot/tree/master/lwr_impedance_controller I found some diagrams and came to this software that was used to generated them and probably to generate the deploy.lua in other packages.

I always looked for an easy way to model controllers and generate deployment files so I am very interested in this software.

I noticed it is not updated any longer. First questions then : Is there a later version somewhere else and if not is this version still used for your deployment ? If not, why ? It looks so handy.

I was eager to try it myself and managed with great difficulties though, to run it in EclipseLuna. 
There were some java environment dependencies I had to fix and some error when opening resources due to FileDialog casting problems.  
I could open the example model but the links do not appear between ports (and apparently they exist in the xml) and I cannot add new links.
![robmod](https://cloud.githubusercontent.com/assets/6583181/10286091/5057a6dc-6b8c-11e5-9c0c-b56dcf0b64dd.png)

I fixed the 100 errors that are basically "description" missing in order to validate the model. This does not solve the missing links.
The warnings are harder to fix as they are warnings about type missing and suggestions to use List<type>. Automatic fix did not work either.

My second question is : How can I regenerate the plugins or tools to maybe automatically fix the warnings for newer java version, because it appears a lot of java code was generated (comments say @generated) 

regards,
Guillaume

**Comment by konradb3** [comment]
Dear Guillaume,
The software used to create those diagrams and generate the code was only prototype.
We currently don't use it.
It have been created with EMF and GMF.
The main meta-model and configuration of GMF is here: https://github.com/konradb3/control-modeler/tree/master/robmod .
To be honest i don't remember how to regenerate the plugins. It have been developed just for few days as fast/dirty prototype.

**Comment by guihomework** [comment]
Thanks for the honest answer. I must say, being unfamiliar with eclipse and not programming java, I never got that far on a prototype, so I was happy to stumble upon a software that appeared to do something useful. 
From your information, I will look again on EMF and GMF and maybe be able to use the model to re-create the plugins.  If I manage to get something useful I will fork and push the fixes for newer Eclipse.

Thanks
